version: "3.5"

networks:
  stellar-testnet:
    name: ${TESTNET_NAME:-stellar_testnet}

services:
  stellar-horizon:
    image: satoshipay/stellar-horizon:latest
    container_name: stellar-horizon
    restart: on-failure
    ports:
    - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:unic_iff@stellar-core-postgres/stellar_horizon_db?sslmode=disable
      - STELLAR_CORE_DATABASE_URL=postgres://postgres:unic_iff@stellar-core-postgres/stellar-genesis?sslmode=disable
      - STELLAR_CORE_URL=http://stellar-genesis:11626
      - HISTORY_ARCHIVE_URLS=http://stellar-archive-publisher:80
      - NETWORK_PASSPHRASE=Standalone UNIC_IFF Network ; 2022          
      - INGEST=true
    networks:
      - stellar-testnet
